# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Base16"
license = "MIT"
licenselink = "http://htdvisser.mit-license.org/"
description = "A simple aqua inspired theme"
homepage = "https://github.com/gnyman/hugo-theme-aqua"
tags = ["blog", "syntax highlighting"]
features = ["blog", "syntax highlighting"]
min_version = 0.140

[author]
  name = "Gabriel Nyman"
  homepage = "https://nyman.re"
